### ISSUE TITLE
the 1.20.2 file has been misplaced

### ISSUE THREAD

**Issue by Kaiji-Key** [KosmoMoustache/MusicNotification#12]
it seems that, when you updated to 1.20.4, the 1.20.2 file was removed from modrinth, as now, when i click download on the 1.20.2 file, it downloads the 1.20.4 file instead. 
i checked for 1.20.1 and 1.20.4 and then both downloaded the correct files, it's just 1.20.2 that's messed up. 

if you could fix this issue, that'd be great, because as of now, i have to disable the mod.

**Comment by Kaiji-Key** [comment]
note:
i just downloaded the 1.20.2 file from here on github as well as from curseforge, so the file has seemingly been misplaced only on modrinth

**Comment by KosmoMoustache** [comment]
it's fixed, my fault, my workflow is terrible
