### ISSUE TITLE
Compatibility issue with mod Better Recipe Book

### ISSUE THREAD

**Issue by Kaiji-Key** [KosmoMoustache/MusicNotification#13]
so i have the correct file now, however, it's making my game crash before it fully loads in. this is the error I'm getting:

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector playSound(Lnet/minecraft/class_368$class_369;Lnet/minecraft/class_1144;)V in mixins.clientmusic.json:MixinToastManagerEntry from mod musicnotification failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap musicnotification-refmap.json
--
1465 | at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
1466 | at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
1467 | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
1468 | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
1469 | at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
1470 | at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
1471 | at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
1472 | at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
1473 | ... 18 more

i can send the full log if you'd like.

i should also mention that i have been using this mod for a few weeks now with no issues, it's something that just changed. also, i disabled it and my game loaded properly

**Comment by KosmoMoustache** [comment]
send the full log please

**Comment by Kaiji-Key** [comment]
https://mclo.gs/bRLnNMf

**Comment by KosmoMoustache** [comment]
It's a compatibility issue with the mod Better Recipe Book. version 1.5.1 fix it, but you will not be able to configure the mute setting of MusicNotification.
