### ISSUE TITLE
Incorrect authors for 3 C&C songs

### ISSUE THREAD

**Issue by BeeTeeKay64** [KosmoMoustache/MusicNotification#19]
Some songs from the Caves and Cliffs OST were improperly credited.

"Comforting Memories", "Floating Dream", and "An Ordinary Day" were all credited to Lena Raine, when they should be credited to Kumi Tanioka, because she is the real composer for those three pieces.

**Comment by KosmoMoustache** [comment]
Fixed, thank you!
