### ISSUE TITLE
New textures for the music discs

### ISSUE THREAD

**Issue by YaCCBoy** [KosmoMoustache/MusicNotification#2]
This is a personal opinion, but I think the textures used for the music discs in the notifications could use a refresh. They are currently really only a scaled down and blurred version of the official album art, and they really don't look good in Minecraft in my opinion.

Here is a `toasts.png` I made with new discs, which I think look much better and better match Minecraft's art direction.
![toasts](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/aa015d03-0613-4510-b2a4-0da7040ba7f7)
Soundtracks that are attached with a disc are represented by that disc, and other soundtracks have a disc made to look like their album art. Personnally, I don't think the three 1.13 music tracks are different enough to warrant a unique disc for each of them, even if they are singles and have different (but similar) album arts. So, their disc was made by combining colors found in the three album arts.

Other than that, this is really a great mod!

**Comment by KosmoMoustache** [comment]
Thanks for the feedback, i've updated with your textures!
