### ISSUE TITLE
Suggestion: allow mods to provide their own musics.json

### ISSUE THREAD

**Issue by Partonetrain** [KosmoMoustache/MusicNotification#21]
It'd be really neat if a mod's music discs could display what number a song is on an album.

Musics.jsons are limited to Minecraft's music:
https://github.com/KosmoMoustache/MusicNotification/blob/1.20.1/src/main/java/net/kosmo/music/ClientMusic.java#L84-L89

**Comment by KosmoMoustache** [comment]
Version 1.6.0 will allow mods and ressource pack to use musics.json. See the new file schema [here](https://github.com/KosmoMoustache/MusicNotification/blob/1.20.4/src/main/resources/assets/musicnotification/musics.json).
