### ISSUE TITLE
[Suggestion] Ability to select and play Ambiance Sounds

### ISSUE THREAD

**Issue by WildFyr16** [KosmoMoustache/MusicNotification#27]
This would be super useful for Resource pack creators to test if their replacement music added and works correctly. I already use this to test the replaced music in [my resource pack](https://github.com/WildFyr16/zelda-music) and it has been extremely useful to simply press a button to hear the music. Additionally, the ability to test the ambiance music as well would make this the perfect mod for resource pack creators too.

Plus some of the ambient music might be nice for people to listen to, if they are into hearing all those cave noises haha

**Comment by mr-dexter-ssj** [comment]
Already possible, just open the mod's settings and enable debug mode

**Comment by KosmoMoustache** [comment]
Sorry for the late reply, like @Henry-SSJ said you can play ambiant sounds from the debug mode.
