### ISSUE TITLE
add ability to make toast persistent throughout song?

### ISSUE THREAD

**Issue by alien-sunset** [KosmoMoustache/MusicNotification#30]
or maybe a toggle to show the info if you missed it when the song started?

i'm sometimes a bit oblivious and miss it when the announcement first shows.
(also the screenshots show an option to adjust how long the toast displays, but i don't see that in my config v1.6.1 for 1.20.4)

**Comment by KosmoMoustache** [comment]
I'm working on a gui where you can see the current played song and the past ones. I have remove the option to adjust how long toast are displayed because there is a option in vanilla now, so it's kinda redondant

**Comment by alien-sunset** [comment]
> I have remove the option to adjust how long toast are displayed because there is a option in vanilla now, so it's kinda redundant

i was completely unaware of this, and a quick google is giving me nothing helpful, can you point to where this can be done?

**Comment by KosmoMoustache** [comment]
Notification time in accessibility settings

![image](https://github.com/KosmoMoustache/MusicNotification/assets/34519077/49371df6-a0c0-4870-93a6-ba0623374f32)

**Comment by KosmoMoustache** [comment]
Is your issue resolved?

**Comment by alien-sunset** [comment]
well, yes and no

i can now make the toast last quite a while, but having the little banner up there constantly can be a bit intrusive, and it applies to all toasts including advancements., so if i get an advancement after a song starts playing i have that advancement notification for ages... and I still don't know what song is playing.

i suppose the issue could be amended to specifically request a toggle to bring up the toast when requested?
but if you get the gui with teh list of current and past played songs that may take care of the issue as well...

**Comment by KosmoMoustache** [comment]
I've added an history menu in version [2.0.0](https://modrinth.com/mod/music-notification/version/2.0.0)
I'm sorry for the late response
