### ISSUE TITLE
[Suggestion] Textures for all music discs

### ISSUE THREAD

**Issue by carotteatomique** [KosmoMoustache/MusicNotification#33]
Currently, all the music of an update's soundtrack is represented by this update's flagship music disc. Caves & Cliffs is represented by Otherside, Trails & Tales by Relic, etc. This works when a new update adds one music disc.

However, 1.21 will add three new music discs to the game: Creator, Creator (Music Box) and Precipice. We can't really use one of these to represent the rest of the soundtrack, because "the rest of the soundtrack" also includes the two other discs, which would be confusing for players. Adding the two others as an exception could work, but it would be inconsistent with the rest of the music.

So I would like to propose a change: Every music disc gets it's own texture, and the rest of the soundtrack gets a new album-specific texture, independent from an existing music disc. And I have already made these textures!

Generic textures (includes the albums as well as the textures for generic and modded discs):

(In order from left to right: Generic, Modded, Volume Alpha, Volume Beta, Update Aquatic, Nether Update, Caves & Cliffs, Wild Update, Trails & Tales, Tricky Trials)

![Generic disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/230d1aba-74e0-4dc3-8eec-53768226f59b) ![Modded disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/43063355-84ad-4bd4-aa07-06cc99d0a17f) ![Volume Alpha disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/9dbe4857-41e0-48ac-b240-febe9464405a) ![Volume Beta](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/8bac914b-291a-444a-b2da-15bb903d2fe8) ![Update Aquatic disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/71d36924-1dd7-4102-b453-0d3d6c5a472b) ![Nether Update disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/9957a3d7-6da6-4a25-9cab-4d6ade1206b6) ![Caves & Cliffs disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/7a5ed461-51bd-4967-b3ce-f1f67dea7f67) ![Wild Update disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/0e737525-9c81-4187-9bef-db7be4c4f78a) ![Trails & Tales disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/ea5f5922-62af-4b8c-8277-606fa5ef158e) ![Tricky Trials disc](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/b077e5b8-f013-4c8d-8585-13d4c4518e3b)

Disc-specific textures:

(In order from left to right: 13, cat, blocks, chirp, far, mall, mellohi, stal, strad, ward, wait, 11, Pigstep, otherside, 5, Relic, Creator, Creator (Music Box), Precipice)

![13](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/07c049c2-1d8c-45b0-a779-b6cc64997f0b) ![cat](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/6c6d6424-7eb3-4f5d-ad41-b92b53399bad) ![blocks](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/2a3f868e-4c37-4710-914b-7686d89d9046) ![chirp](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/2e15bd3f-a265-4f45-8f43-eeb4d2a18677) ![far](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/74398ac6-80d1-4b31-99ab-00d5f4825bab) ![mall](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/bbeaf52e-89ea-48de-90dc-fd1ef7c4f635) ![mellohi](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/74e68358-330d-494f-9925-495913072793) ![stal](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/e8927771-620f-4898-acda-767a57d8b517) ![strad](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/223c02df-14cd-4926-b317-f3674d783ff9) ![ward](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/7e080a4f-1f86-41df-894a-467077d66370) ![wait](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/62cee21f-7dec-414f-98a4-427059e8bc53) ![11](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/ab201873-094e-4d23-8e2f-f1ffcf81fcce) ![pigstep](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/3e5f3a15-0c47-4ac4-91a9-9c10f67939c3) ![otherside](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/f26afdfd-456d-46bd-afd4-4f88567a0802) ![5](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/dd105f61-d808-4d78-ae80-89ffc5d5c00c) ![relic](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/260fbf08-c1ca-4efc-9b68-4bc49d98f1b9) ![creator](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/1d273d43-5857-4e24-a85b-edf9c2ea6c2f) ![creator_music_box](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/d0ada47b-e3aa-44c1-845b-6fdd3abf5568) ![precipice](https://github.com/KosmoMoustache/MusicNotification/assets/87284322/2ad45377-43ee-49db-b2ee-78035dcc3512)

For the album music discs, I mostly recolored the center piece to have the colors of their corresponding update's logo. Exceptions are the Volume Alpha, Volume Beta and Update Aquatic discs (which I didn't change from what they were) and the Nether Update disc, which on top of having the color of the update in the center, also has the disc colored like Pigstep. (And I made the very center of the disc look like a Nether portal which I think looks cute)

I also changed the textures of the Generic and Modded discs. The Generic disc looked exactly like the 13 disc, so I changed it to avoid confusion. I made it look like the disc in the mod's icon, and changed the Modded disc to fit (it has the colors of the silver note in the mod icon)

That ends my proposal. Thank you for maintaining this mod! It is amazing all around, I especially like the spinning animation in the toast, it looks really cool :)

All the new textures in one convenient ZIP file as to not have to right-click-save everything: 
[discs.zip](https://github.com/KosmoMoustache/MusicNotification/files/15253292/discs.zip)

**Comment by KosmoMoustache** [comment]
Added in version 2.0.1

Thank you very much for those new icons! The mod will not be same without your icons!
