### ISSUE TITLE
Mute option doesn't work

### ISSUE THREAD

**Issue by antieksi** [KosmoMoustache/MusicNotification#41]
When I set the "Configure toast in and out sound" option to "MUTE_SELF" or "MUTE_ALL", the mod's toasts (or any toast in the game) still produce the popup sound.

I guess that it is the case because some other mods modify the same part of the code that is responsible for toast sounds, so here is my entire mod list:

https://pastebin.com/XSrjyiRB

**Comment by KosmoMoustache** [comment]
Yes it's caused by better recipe book.
