### ISSUE TITLE
[Enhancement] Create an option to remove the toasts when a sound from a noteblock plays

### ISSUE THREAD

**Issue by mr-dexter-ssj** [KosmoMoustache/MusicNotification#48]
I find very annoying that when a noteblock sounds a toast appears, that is especially annoying in servers that play music using noteblocks, so please create a button to toggle this function

**Comment by KosmoMoustache** [comment]
I will fix it, unfortunately I don't have access to a proper computer right now to work on that

**Comment by KosmoMoustache** [comment]
I've added a config option to add sounds event that will be ignored when displaying notification defaulting to "minecraft:block.note_block.*".

**Comment by mr-dexter-ssj** [comment]
Thanks
