### ISSUE TITLE
[Suggestion] Mod Discs

### ISSUE THREAD

**Issue by SkyKingPX** [KosmoMoustache/MusicNotification#54]
Hello, I wonder if there is any way to add Music Discs from other mods to the disc-gui

**Comment by KosmoMoustache** [comment]
Prior to 1.20.6 excluded you need a resource pack to add custom music disc to the gui. After 1.20.6 included, they are automatically added when you enter a world with custom/modded music discs

**Comment by SkyKingPX** [comment]
I use 1.20.1 for my modpack so which resourcepack is it?

**Comment by KosmoMoustache** [comment]
You have to make it yourself, there is documentation [here](https://github.com/KosmoMoustache/MusicNotification/blob/next/DOCS.md) and you can find example [here](https://github.com/KosmoMoustache/MusicNotification/tree/next/test/custom_musics.json)

**Comment by SkyKingPX** [comment]
I wanted to update my modpack to 1.21.1 anyways so I'll just wait for everything to update
