### ISSUE TITLE
[suggestion] ability to pause or mute music via keybind.

### ISSUE THREAD

**Issue by alien-sunset** [KosmoMoustache/MusicNotification#56]
not just stop the current music, but stop it starting another music afterwords. 

something that can be toggled on and off easily while, say streaming or recording, without having to constantly visit the player menu

**Comment by KosmoMoustache** [comment]
Why not just muting music in the Music & Sounds options?

**Comment by alien-sunset** [comment]
Because there are other music related things that I do want to hear.
We have simple voice chat and audio player which also interact via the music channel, and i still want to hear those things,

because sometimes I only want to mute for a few minutes, and having to go into the menu and fiddle with the settings takes time and is distracting, especially while streaming.

**Comment by KosmoMoustache** [comment]
will work on that
