### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by Zorklis** [KosmoMoustache/MusicNotification#9]
Please, I love this mod

**Comment by KosmoMoustache** [comment]
You can get it now on [Modrinth](https://modrinth.com/mod/music-notification/version/1.5.0+1.20.2) and Github, soon on CurseForge

**Comment by Zorklis** [comment]
Great! I prioritize Modrinth anyways so it's good to see it get posted there.
Checked it out, tested, works! Thank you :)
